### ISSUE TITLE
Searching for List.replicate shows me 'iterate' (an alias) in the finder

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/codebase-ui#148] opened 2021-06-09 13:31 UTC
<img width="841" alt="Screen Shot 2021-06-09 at 8 30 21 AM" src="https://user-images.githubusercontent.com/11074/121364162-25b78f80-c8fd-11eb-874c-75924654b4b5.png">

But it's also weirdly missing the FQN info. What namespace is iterate in?

**Comment by hojberg** [comment] 2021-06-09 13:42
I think this is a duplicate of https://github.com/unisonweb/codebase-ui/issues/64

**Comment by pchiusano** [comment] 2021-06-09 13:50
Yeah agree it seems like a dupe

**Closed** 2021-06-09 13:50 UTC
